# Generated by Django 5.2.6 on 2025-11-16 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('db478415-fb4f-45c4-97d9-3a0c265ea407'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('ea90a1cd-2ca2-4a5c-a7dc-93c74aaa9ea5'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('a7c67ea8-1861-458e-9f5e-11dc1d8b16ba'), primary_key=True, serialize=False, unique=True),
        ),
    ]
