# Generated by Django 5.2.6 on 2025-11-17 07:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_bookings_booking_id_alter_customuser_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('a45b0899-02a1-43cc-b8b8-247336e4a9ca'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('b35a72d9-ed0a-4350-8fc0-2408af22bed4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('942b8189-6d35-445b-bbca-1a66c9b6d4f4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.UUIDField(db_index=True, default=uuid.UUID('ea98098f-6a88-45ff-a149-da27fd230952'), primary_key=True, serialize=False, unique=True)),
                ('ratings', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, "Ratings can't be less than 1"), django.core.validators.MaxValueValidator(5, "Ratings can't be greater than 5")])),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
