# Generated by Django 5.2.6 on 2025-11-30 21:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_bookings_booking_id_alter_bookings_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('392eaa3d-ceae-4870-b6b8-de6b151e3018'), primary_key=True, serialize=False, unique=True),
        ),
    ]
