# Generated by Django 6.0.1 on 2026-01-15 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_bookings_booking_id_alter_customuser_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('6c8b224e-2b29-4b79-9635-605e4a7831bd'), primary_key=True, serialize=False, unique=True),
        ),
    ]
