# Generated by Django 6.0.1 on 2026-01-15 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_reviews_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('dc5dea6b-db7a-4618-9ee1-47423c6e9711'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('pmt_method', models.CharField(max_length=200)),
                ('pmt_status', models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('pmt_ref', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
