# Generated by Django 6.0.1 on 2026-01-15 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_reviews_review_id_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='booking',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='listings.bookings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('e9fbd30a-1821-4453-bf61-7fc527fb2437'), primary_key=True, serialize=False, unique=True),
        ),
    ]
