# Generated by Django 6.0.1 on 2026-01-15 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_payments_booking_alter_reviews_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='listings.bookings'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('addf5353-0250-43fe-b0b0-493de0871a62'), primary_key=True, serialize=False, unique=True),
        ),
    ]
