# Generated by Django 5.2.6 on 2025-10-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='Bookings_type',
        ),
        migrations.AddField(
            model_name='bookings',
            name='bookings_type',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('FLIGHT', 'Flight'), ('PACKAGE', 'Package')], default='HOTEL', editable=False, max_length=10),
        ),
    ]
